### PR TITLE
Added Automatic PHPDoc generation

### PR DESCRIPTION
**Pull request by GaeaKat**
the PR should when a push to Master occurs, run phpdocumentor on the src/ directory, putting the output in doc/ it will use phpdoc.dist.xml for settings.

### CODE REVIEW

**Comment by KatrinaAS** [comment]
Hmm, doesn't seem to like PRs, should I remove that from the workflow?

**Comment by Vassyli** [comment]
Interesting idea!

A few questions:

- Is there a specific reason why you are using the action from your own cloned repository instead of the original one?
- The action states it supports doc generation "up to pHP version 7.0", but I've switched to 8.0 meanwhile.
- Does PHPDoc recognize typehints? I'm not in favour of keeping typehints and Docblocks in sync - eventually, I want to get rid typehints in doc blocks.

**Comment by GaeaKat** [comment]
No problem.
I use an action from my own repo to add in PHP-8 compatibility as as you point out, the original is only PHP 7.

Regarding the typehints, I am unsure, And will test shortly

**Comment by GaeaKat** [comment]
Tested by adding the following function to Action as a test with no Docblock
```php
public function i_test_things(string $puppy,int $kitty,ActionGroup $pop) {

    }
```
    
    it outputs this as expected.
    
Screenshot 2021-09-05 at 21 59 05

**Comment by Vassyli** [comment]
Thank you a lot.

**Comment by Vassyli** [comment]
Contributes to #33

**Comment by Vassyli** [comment]
This seems to fail as the master branch is protected. Any ideas?

**Pull request merged**
