### PR TITLE
Make bin\daenerys extensible

### LINKED ISSUE #40: Make bin\daenerys extensible
Make bin\daenerys extensible so that crate's can take that console application and extend upon it. It's desirable that, if a crate wants to offer additional console commands, that it can extend upon the core's console application to have a common interface for the end-user.

### PR DESCRIPTION
**Pull request by Vassyli**
This commit makes bin\daenerys extensible for additional commands

Fixes #40.

### CODE REVIEW

**Comment by austenmc** [comment]
How will this work?

**Comment by Vassyli** [comment]
I can take the daenerys utils binary and register commands in the crate using the static function to provide additional features. Something along the lines of

```
Main::registerCommand(new CrateUserCreateCommand())
```

**Comment by austenmc** [comment]
Couple of things:
1. Do you have a concrete use case for this yet? If not, let's wait to add complexity until we have a real use case.
2. `Main::registerCommand()` would only work while the `daenerys` tool is running. To make this really extensible, `daenerys` should fire a hook and listeners can return commands in the event handler.

**Comment by Vassyli** [comment]
I thought about extending the tool on both sites to provide commands to:
1. Extend with commands to initiate database with default data in core
2. Extend then in crate with commands to create new user

> I'll close this PR and think about it a bit more.

**Pull request closed without merging**
