### PR TITLE
Update README to include more documentation and info about contributing

### PR DESCRIPTION
**Pull request by austenmc**

### CODE REVIEW

**Comment by austenmc** [comment]
(more coming here)

**Comment by Vassyli** [comment]
Thought about the same while looking at the newest dragonprime posts :) Maybe we should add/rephrase stephens [latest post](http://dragonprime.net/index.php?topic=12736.msg106612#msg106612)?

**Comment by austenmc** [comment]
I think you're right to point people away from the DB stuff. That's not the highest pri info to understand. Instead, I'll spend some time tonight documenting our plan for how the pieces fit together---scenes, modules etc.

**Comment by austenmc** [comment]
Killing this PR since it's messed up w/ the merge somehow.

**Pull request closed without merging**
